;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cycle-spacing
        kill-region
        org-beginning-of-line
        org-self-insert-command
        org-shiftright
        string-inflection-underscore
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        rspec-rerun
        ))
